### ISSUE TITLE
TypeError: Can't convert 'bool' object to str implicitly on Windows

### ISSUE THREAD

**Issue by dbobak** [phyllisstein/Pandown#26]
When trying to build a file with Pandown (regardless of the output file format), I'm getting the following errors in the console:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "pandownBuildCommand in C:\Users\deni\AppData\Roaming\Sublime Text 3\Installed Packages\Pandown.sublime-package", line 97, in run
  File "pandownBuildCommand in C:\Users\deni\AppData\Roaming\Sublime Text 3\Installed Packages\Pandown.sublime-package", line 365, in buildPandocCmd
TypeError: Can't convert 'bool' object to str implicitly
```

My configuration:
Windows 8.1 Polish version
Sublime Text 3 build 3083

regards,
Darek

**Comment by openmedi** [comment]
I have a similiar/related error on OS X 10.11.2 and ST3 Build 3038.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "pandownBuildCommand in /Users/martin/Library/Application Support/Sublime Text 3/Installed Packages/Pandown.sublime-package", line 111, in run
  File "pandownBuildCommand in /Users/martin/Library/Application Support/Sublime Text 3/Installed Packages/Pandown.sublime-package", line 163, in openAndDisplay
TypeError: Can't convert 'bytes' object to str implicitly
```
